version: '3'

services:

 myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql

 mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scrapjob
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"