version: '3.1'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scrapjob
      MYSQL_PASSWORD: root
    networks:
      rsf:

  myapp:
    container_name: myapp
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/scrapjob
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    networks:
      rsf:

networks:
  rsf: